"""Added <your-change>"""

revision = '4bc45374c150'
down_revision = '04c02a6543db'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa



def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###

def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
