"""Add ip and mac to TimeLog"""

revision = '8ed339345ebb'
down_revision = '4bc45374c150'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa



def upgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.add_column('timelogs', sa.Column('ip', sa.String(), nullable=True))
    op.add_column('timelogs', sa.Column('mac', sa.String(), nullable=True))
    # ### end Alembic commands ###

def downgrade():
# ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('timelogs', 'mac')
    op.drop_column('timelogs', 'ip')
    # ### end Alembic commands ###
